---
title: "Untitled"
author: "Greta Gadbois"
date: "September 7, 2015"
output: html_document
---



```{r}
library(plyr)

rowVar <- function(x) {
  rowSums((x - rowMeans(x))^2)/(dim(x)[2] - 1)}

antRuns = read.csv('SADModel2-sorted.csv')
antRuns["LN"] = rowMeans(cbind(antRuns$LN1, antRuns$LN2, antRuns$LN3, antRuns$LN4))
antRuns["LNvar"] = rowVar(cbind(antRuns$LN1, antRuns$LN2, antRuns$LN3, antRuns$LN4))
antRuns["LW"] = rowMeans(cbind(antRuns$LW1, antRuns$LW2, antRuns$LW3, antRuns$LW4))
antRuns["LWvar"] = rowVar(cbind(antRuns$LW1, antRuns$LW2, antRuns$LW3, antRuns$LW4))
antRuns["SN"] = rowMeans(cbind(antRuns$SN1, antRuns$SN2, antRuns$SN3, antRuns$SN4))
antRuns["SNvar"] = rowVar(cbind(antRuns$SN1, antRuns$SN2, antRuns$SN3, antRuns$SN4))
antRuns["SW"] = rowMeans(cbind(antRuns$SW1, antRuns$SW2, antRuns$SW3))
antRuns["SWvar"] = rowVar(cbind(antRuns$SW1, antRuns$SW2, antRuns$SW3))
antRuns[1:10,]


aggRuns <- ddply(antRuns, c("LNperc", "LWperc", "SNperc", "SWperc"), summarise,
                 reps = length(LN),
                 LNmean = mean(LN),
                 LNvar = mean(LNvar),
                 LNsd = sqrt(mean(LNvar)),
                 LWmean = mean(LW),
                 LWvar = mean(LWvar),
                 LWsd = sqrt(mean(LWvar)),
                 SNmean = mean(SN),
                 SNvar = mean(SNvar),
                 SNsd = sqrt(mean(SNvar)),
                 SWmean = mean(SW),
                 SWvar = mean(SWvar),
                 SWsd = sqrt(mean(SWvar)))

aggRuns[1:10,]

incomplete = aggRuns[aggRuns$reps != 10, ]
incomplete
```



```{r}
smallVlarge = subset(aggRuns, SNperc == SWperc & LNperc == LWperc & SNperc + LNperc == 1)
smallVlarge

smallperc = smallVlarge$SNperc
numSmall = smallVlarge$SNmean + smallVlarge$SWmean
numSmallsd = sqrt(mean(cbind(smallVlarge$SNvar, smallVlarge$SWvar)))
numLarge = smallVlarge$LNmean + smallVlarge$LWmean
numLargesd = sqrt(mean(cbind(smallVlarge$LNvar, smallVlarge$LWvar)))

plot(smallperc, numSmall, col = 'black')
points(smallperc, numLarge, col = 'red')



```
